/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.pw.ii.pap.z29;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        
    }
}
